set -g mouse on
set -g base-index 1
setw -g pane-base-index 1

set-option -g renumber-windows on
set-option -g status-interval 1

set -g prefix C-s
unbind C-b
bind C-s send-prefix

setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -s extended-keys on

# pomodoro
set -g status-right "#{pomodoro} | %H:%M"

# plugins

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-contrib/tmux-pomodoro'

run '~/.tmux/plugins/tpm/tpm'
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"
set -g status-style "bg=#1e1e2e,fg=#cdd6f4"
