# appeareance
font_family     CaskaydiaCove Nerd Font
bold_font       Cascadia Code Bold
italic_font     Cascadia Code Italic
symbol_map      U+0600-U+06FF,U+FB50-U+FDFF,U+FE70-U+FEFF SF Arabic
font_size 16.0

# cursor
cursor_shape block
cursor_trail 1
shell_integration no-cursor

# background
background #1e1e2e
background_opacity 0.5

# window
confirm_os_window_close 0

# misc
enable_audio_bell no
copy_on_select yes
window_padding_width 5 10
