font_family      CaskaydiaCove Nerd Font
bold_font        Cascadia Code Bold
italic_font      Cascadia Code Italic
symbol_map U+0600-U+06FF,U+FB50-U+FDFF,U+FE70-U+FEFF SF Arabic
font_size 16.0

hide_window_decorations yes

window_padding_width 10

cursor_shape block
cursor_blink_interval -1

copy_on_select yes

background #1e1e2e

enable_audio_bell no
