backend = "glx";
vsync = true;

blur-method = "dual_kawase";
blur-strength = 2;
blur-background = true;
blur-background-frame = true;
blur-background-fixed = false;

inactive-opacity = 0.95;
active-opacity = 0.95;
