[opener]
open = [
    { run = "xdg-open %s", orphan = true }
]
edit = [
    { run = "nvim %s", block = true }
]

[open]
prepend_rules = [
    { mime = "text/*", use = "edit" },
    { mime = "image/*", use = "open"},
    { mime = "application/*", use = "open"},
    { mime = "text/*", use = "edit"}
]
